# Specify a base image
FROM node:18 AS build 

# Change working directory
WORKDIR /usr/app

# Copy in the app and weights
COPY ./ /usr/app

# Install dependencies
RUN yarn global add turbo
RUN yarn install

ENV NODE_ENV=production

EXPOSE 3001

CMD turbo start --filter='./apps/auth'
