# Specify a base image
FROM node:18 AS build

# Set ARGs
ARG ORIGINS
ARG OAUTH_CLIENT_ID
ARG OAUTH_CLIENT_SECRET

# Change working directory
WORKDIR /usr/app

# Copy in the app and weights
COPY ./ /usr/app

# Install dependencies
RUN yarn global add turbo
RUN yarn install

# Set ENVs
ENV NODE_ENV=production
ENV PORT=3001
ENV ORIGINS=${ORIGINS}
ENV OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
ENV OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}

EXPOSE 3001

CMD turbo start --filter='./apps/auth'
